# -*- coding: utf-8 -*-
"""LogisticRegression-FakeNewsPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    

## **Import Required Innitial Dependencies**
"""

import numpy as np
import pandas as pd

"""## **Load the training datasets**"""

train_data = pd.read_csv('/content/train.csv')

train_data.head()

print(train_data.shape)

"""# **Data Pre-processing**

Check for null values and replace the null values with empty string
"""

# Check for null values of train data set
train_data.isnull().sum()

# Replace the null value with empty string in train data
train_data = train_data.fillna('')

# After replacing the null values with empty string in train data
train_data.isnull().sum()

"""Identify the stopwords"""

# Import stopwords
from nltk.corpus import stopwords

import nltk
nltk.download('stopwords')

# Print stopwords
print(stopwords.words('english'))

"""Merge the author column and title colum"""

# Merge the author column and title colum in train dataset
train_data['merged_title_and_author'] = train_data['author']+[' ']+train_data['title']

print(train_data['merged_title_and_author'])

"""## **Seperating indipendent and dependent variables**"""

# Removing label column from training data set
X = train_data.drop(columns='label', axis=1)

print(X)

# Store label in Y variable 
Y = train_data['label']

print(Y)